export {
  DataType,
  Field,
  Order,
  Select,
  SelectAll,
  SelectGreatest,
  SelectLeast,
  SelectRegrIntercept,
  SelectRegrR2,
  SelectRegrSlope,
  SystemFields,
  Where,
} from "https://deno.land/x/soda@0.4.5/mod.ts";

export { AsGegevensEegUitvoering } from "./AsGegevensEegUitvoering.ts";
export type { AsGegevensEegUitvoering_ResponseData } from "./AsGegevensEegUitvoering.ts";
export { BasisgegevensEegUitvoering } from "./BasisgegevensEegUitvoering.ts";
export type { BasisgegevensEegUitvoering_ResponseData } from "./BasisgegevensEegUitvoering.ts";
export { BrandstoffenOpPc4 } from "./BrandstoffenOpPc4.ts";
export type { BrandstoffenOpPc4_ResponseData } from "./BrandstoffenOpPc4.ts";
export { CarrosserieUitvoering } from "./CarrosserieUitvoering.ts";
export type { CarrosserieUitvoering_ResponseData } from "./CarrosserieUitvoering.ts";
export { CarrosserieUitvoeringKlasse } from "./CarrosserieUitvoeringKlasse.ts";
export type { CarrosserieUitvoeringKlasse_ResponseData } from "./CarrosserieUitvoeringKlasse.ts";
export { CarrosserieUitvoeringNummeriekeCode } from "./CarrosserieUitvoeringNummeriekeCode.ts";
export type { CarrosserieUitvoeringNummeriekeCode_ResponseData } from "./CarrosserieUitvoeringNummeriekeCode.ts";
export { EegVoertuigtypegoedkeuring } from "./EegVoertuigtypegoedkeuring.ts";
export type { EegVoertuigtypegoedkeuring_ResponseData } from "./EegVoertuigtypegoedkeuring.ts";
export { ErkendeBedrijven } from "./ErkendeBedrijven.ts";
export type { ErkendeBedrijven_ResponseData } from "./ErkendeBedrijven.ts";
export { Erkenningen } from "./Erkenningen.ts";
export type { Erkenningen_ResponseData } from "./Erkenningen.ts";
export { Gebreken } from "./Gebreken.ts";
export type { Gebreken_ResponseData } from "./Gebreken.ts";
export { GeconstateerdeGebreken } from "./GeconstateerdeGebreken.ts";
export type { GeconstateerdeGebreken_ResponseData } from "./GeconstateerdeGebreken.ts";
export { GeoCarpool } from "./GeoCarpool.ts";
export type { GeoCarpool_ResponseData } from "./GeoCarpool.ts";
export { GeoParkeerGarages } from "./GeoParkeerGarages.ts";
export type { GeoParkeerGarages_ResponseData } from "./GeoParkeerGarages.ts";
export { GeoPenr } from "./GeoPenr.ts";
export type { GeoPenr_ResponseData } from "./GeoPenr.ts";
export { HandelsbenamingUitvoering } from "./HandelsbenamingUitvoering.ts";
export type { HandelsbenamingUitvoering_ResponseData } from "./HandelsbenamingUitvoering.ts";
export { KentekenVoertuigen } from "./KentekenVoertuigen.ts";
export type { KentekenVoertuigen_ResponseData } from "./KentekenVoertuigen.ts";
export { KentekenVoertuigenAssen } from "./KentekenVoertuigenAssen.ts";
export type { KentekenVoertuigenAssen_ResponseData } from "./KentekenVoertuigenAssen.ts";
export { KentekenVoertuigenBijzonderheden } from "./KentekenVoertuigenBijzonderheden.ts";
export type { KentekenVoertuigenBijzonderheden_ResponseData } from "./KentekenVoertuigenBijzonderheden.ts";
export { KentekenVoertuigenBrandstof } from "./KentekenVoertuigenBrandstof.ts";
export type { KentekenVoertuigenBrandstof_ResponseData } from "./KentekenVoertuigenBrandstof.ts";
export { KentekenVoertuigenCarrosserie } from "./KentekenVoertuigenCarrosserie.ts";
export type { KentekenVoertuigenCarrosserie_ResponseData } from "./KentekenVoertuigenCarrosserie.ts";
export { KentekenVoertuigenCarrosserieSpecificatie } from "./KentekenVoertuigenCarrosserieSpecificatie.ts";
export type { KentekenVoertuigenCarrosserieSpecificatie_ResponseData } from "./KentekenVoertuigenCarrosserieSpecificatie.ts";
export { KentekenVoertuigenRupsbanden } from "./KentekenVoertuigenRupsbanden.ts";
export type { KentekenVoertuigenRupsbanden_ResponseData } from "./KentekenVoertuigenRupsbanden.ts";
export { KentekenVoertuigenSubcategorieVoertuig } from "./KentekenVoertuigenSubcategorieVoertuig.ts";
export type { KentekenVoertuigenSubcategorieVoertuig_ResponseData } from "./KentekenVoertuigenSubcategorieVoertuig.ts";
export { KentekenVoertuigenVoertuigklasse } from "./KentekenVoertuigenVoertuigklasse.ts";
export type { KentekenVoertuigenVoertuigklasse_ResponseData } from "./KentekenVoertuigenVoertuigklasse.ts";
export { Keuringen } from "./Keuringen.ts";
export type { Keuringen_ResponseData } from "./Keuringen.ts";
export { MeldingenKeuringsinstantie } from "./MeldingenKeuringsinstantie.ts";
export type { MeldingenKeuringsinstantie_ResponseData } from "./MeldingenKeuringsinstantie.ts";
export { MerkUitvoeringToegestaan } from "./MerkUitvoeringToegestaan.ts";
export type { MerkUitvoeringToegestaan_ResponseData } from "./MerkUitvoeringToegestaan.ts";
export { MotorUitvoering } from "./MotorUitvoering.ts";
export type { MotorUitvoering_ResponseData } from "./MotorUitvoering.ts";
export { MotorUitvoeringBrandstof } from "./MotorUitvoeringBrandstof.ts";
export type { MotorUitvoeringBrandstof_ResponseData } from "./MotorUitvoeringBrandstof.ts";
export { ParkerenBetaalmethodeGebied } from "./ParkerenBetaalmethodeGebied.ts";
export type { ParkerenBetaalmethodeGebied_ResponseData } from "./ParkerenBetaalmethodeGebied.ts";
export { ParkerenBetaalmethodeVerkooppunt } from "./ParkerenBetaalmethodeVerkooppunt.ts";
export type { ParkerenBetaalmethodeVerkooppunt_ResponseData } from "./ParkerenBetaalmethodeVerkooppunt.ts";
export { ParkerenContactpersoon } from "./ParkerenContactpersoon.ts";
export type { ParkerenContactpersoon_ResponseData } from "./ParkerenContactpersoon.ts";
export { ParkerenGebied } from "./ParkerenGebied.ts";
export type { ParkerenGebied_ResponseData } from "./ParkerenGebied.ts";
export { ParkerenGebiedRegeling } from "./ParkerenGebiedRegeling.ts";
export type { ParkerenGebiedRegeling_ResponseData } from "./ParkerenGebiedRegeling.ts";
export { ParkerenGebiedsbeheerder } from "./ParkerenGebiedsbeheerder.ts";
export type { ParkerenGebiedsbeheerder_ResponseData } from "./ParkerenGebiedsbeheerder.ts";
export { ParkerenGebruiksdoel } from "./ParkerenGebruiksdoel.ts";
export type { ParkerenGebruiksdoel_ResponseData } from "./ParkerenGebruiksdoel.ts";
export { ParkerenGeldigheidsinperking } from "./ParkerenGeldigheidsinperking.ts";
export type { ParkerenGeldigheidsinperking_ResponseData } from "./ParkerenGeldigheidsinperking.ts";
export { ParkerenGeldigheidsuitbreiding } from "./ParkerenGeldigheidsuitbreiding.ts";
export type { ParkerenGeldigheidsuitbreiding_ResponseData } from "./ParkerenGeldigheidsuitbreiding.ts";
export { ParkerenGeometrieGebied } from "./ParkerenGeometrieGebied.ts";
export type { ParkerenGeometrieGebied_ResponseData } from "./ParkerenGeometrieGebied.ts";
export { ParkerenGeoVerkooppunt } from "./ParkerenGeoVerkooppunt.ts";
export type { ParkerenGeoVerkooppunt_ResponseData } from "./ParkerenGeoVerkooppunt.ts";
export { ParkerenGpsCoordinatenParkeerlocatie } from "./ParkerenGpsCoordinatenParkeerlocatie.ts";
export type { ParkerenGpsCoordinatenParkeerlocatie_ResponseData } from "./ParkerenGpsCoordinatenParkeerlocatie.ts";
export { ParkerenIndexStatischEnDynamisch } from "./ParkerenIndexStatischEnDynamisch.ts";
export type { ParkerenIndexStatischEnDynamisch_ResponseData } from "./ParkerenIndexStatischEnDynamisch.ts";
export { ParkerenInUitgang } from "./ParkerenInUitgang.ts";
export type { ParkerenInUitgang_ResponseData } from "./ParkerenInUitgang.ts";
export { ParkerenParkeeradres } from "./ParkerenParkeeradres.ts";
export type { ParkerenParkeeradres_ResponseData } from "./ParkerenParkeeradres.ts";
export { ParkerenParkeergebied } from "./ParkerenParkeergebied.ts";
export type { ParkerenParkeergebied_ResponseData } from "./ParkerenParkeergebied.ts";
export { ParkerenParkeergebiedContactpersoon } from "./ParkerenParkeergebiedContactpersoon.ts";
export type { ParkerenParkeergebiedContactpersoon_ResponseData } from "./ParkerenParkeergebiedContactpersoon.ts";
export { ParkerenParkingOpen } from "./ParkerenParkingOpen.ts";
export type { ParkerenParkingOpen_ResponseData } from "./ParkerenParkingOpen.ts";
export { ParkerenParkingToegang } from "./ParkerenParkingToegang.ts";
export type { ParkerenParkingToegang_ResponseData } from "./ParkerenParkingToegang.ts";
export { ParkerenRegeling } from "./ParkerenRegeling.ts";
export type { ParkerenRegeling_ResponseData } from "./ParkerenRegeling.ts";
export { ParkerenSpecialeDag } from "./ParkerenSpecialeDag.ts";
export type { ParkerenSpecialeDag_ResponseData } from "./ParkerenSpecialeDag.ts";
export { ParkerenSpecificatiesParkeergebied } from "./ParkerenSpecificatiesParkeergebied.ts";
export type { ParkerenSpecificatiesParkeergebied_ResponseData } from "./ParkerenSpecificatiesParkeergebied.ts";
export { ParkerenTariefberekening } from "./ParkerenTariefberekening.ts";
export type { ParkerenTariefberekening_ResponseData } from "./ParkerenTariefberekening.ts";
export { ParkerenTariefdeel } from "./ParkerenTariefdeel.ts";
export type { ParkerenTariefdeel_ResponseData } from "./ParkerenTariefdeel.ts";
export { ParkerenTijdvak } from "./ParkerenTijdvak.ts";
export type { ParkerenTijdvak_ResponseData } from "./ParkerenTijdvak.ts";
export { ParkerenVerkooppunt } from "./ParkerenVerkooppunt.ts";
export type { ParkerenVerkooppunt_ResponseData } from "./ParkerenVerkooppunt.ts";
export { PlaatsaanduidingUitvoering } from "./PlaatsaanduidingUitvoering.ts";
export type { PlaatsaanduidingUitvoering_ResponseData } from "./PlaatsaanduidingUitvoering.ts";
export { ProductenCatalogus } from "./ProductenCatalogus.ts";
export type { ProductenCatalogus_ResponseData } from "./ProductenCatalogus.ts";
export { SubcategorieUitvoering } from "./SubcategorieUitvoering.ts";
export type { SubcategorieUitvoering_ResponseData } from "./SubcategorieUitvoering.ts";
export { TellerstandoordeelTrendToelichting } from "./TellerstandoordeelTrendToelichting.ts";
export type { TellerstandoordeelTrendToelichting_ResponseData } from "./TellerstandoordeelTrendToelichting.ts";
export { TerugroepActie } from "./TerugroepActie.ts";
export type { TerugroepActie_ResponseData } from "./TerugroepActie.ts";
export { TerugroepActieRisico } from "./TerugroepActieRisico.ts";
export type { TerugroepActieRisico_ResponseData } from "./TerugroepActieRisico.ts";
export { TerugroepActieStatus } from "./TerugroepActieStatus.ts";
export type { TerugroepActieStatus_ResponseData } from "./TerugroepActieStatus.ts";
export { TerugroepInformerenEigenaar } from "./TerugroepInformerenEigenaar.ts";
export type { TerugroepInformerenEigenaar_ResponseData } from "./TerugroepInformerenEigenaar.ts";
export { TerugroepVoertuigMerkType } from "./TerugroepVoertuigMerkType.ts";
export type { TerugroepVoertuigMerkType_ResponseData } from "./TerugroepVoertuigMerkType.ts";
export { TestProducerApi } from "./TestProducerApi.ts";
export type { TestProducerApi_ResponseData } from "./TestProducerApi.ts";
export { ToegevoegdeObjecten } from "./ToegevoegdeObjecten.ts";
export type { ToegevoegdeObjecten_ResponseData } from "./ToegevoegdeObjecten.ts";
export { UitvoeringGebruiksgegevensPerUitgave } from "./UitvoeringGebruiksgegevensPerUitgave.ts";
export type { UitvoeringGebruiksgegevensPerUitgave_ResponseData } from "./UitvoeringGebruiksgegevensPerUitgave.ts";
export { VersnellingsbakUitvoering } from "./VersnellingsbakUitvoering.ts";
export type { VersnellingsbakUitvoering_ResponseData } from "./VersnellingsbakUitvoering.ts";
