export {
  DataType,
  Field,
  Order,
  Select,
  SelectAll,
  SelectGreatest,
  SelectLeast,
  SelectRegrIntercept,
  SelectRegrR2,
  SelectRegrSlope,
  SystemFields,
  Where,
} from "https://deno.land/x/soda@0.4.5/mod.ts";

export { BrandstoffenOpPc4 } from "./BrandstoffenOpPc4.ts";
export type { BrandstoffenOpPc4_ResponseData } from "./BrandstoffenOpPc4.ts";
export { ErkendeBedrijven } from "./ErkendeBedrijven.ts";
export type { ErkendeBedrijven_ResponseData } from "./ErkendeBedrijven.ts";
export { Erkenningen } from "./Erkenningen.ts";
export type { Erkenningen_ResponseData } from "./Erkenningen.ts";
export { Gebieden } from "./Gebieden.ts";
export type { Gebieden_ResponseData } from "./Gebieden.ts";
export { Gebieden } from "./Gebieden.ts";
export type { Gebieden_ResponseData } from "./Gebieden.ts";
export { Gebreken } from "./Gebreken.ts";
export type { Gebreken_ResponseData } from "./Gebreken.ts";
export { GeconstateerdeGebreken } from "./GeconstateerdeGebreken.ts";
export type { GeconstateerdeGebreken_ResponseData } from "./GeconstateerdeGebreken.ts";
export { GeoCarpool } from "./GeoCarpool.ts";
export type { GeoCarpool_ResponseData } from "./GeoCarpool.ts";
export { GeoParkeerGarages } from "./GeoParkeerGarages.ts";
export type { GeoParkeerGarages_ResponseData } from "./GeoParkeerGarages.ts";
export { GeoPenr } from "./GeoPenr.ts";
export type { GeoPenr_ResponseData } from "./GeoPenr.ts";
export { KentekenVoertuigen } from "./KentekenVoertuigen.ts";
export type { KentekenVoertuigen_ResponseData } from "./KentekenVoertuigen.ts";
export { KentekenVoertuigenAssen } from "./KentekenVoertuigenAssen.ts";
export type { KentekenVoertuigenAssen_ResponseData } from "./KentekenVoertuigenAssen.ts";
export { KentekenVoertuigenBijzonderheden } from "./KentekenVoertuigenBijzonderheden.ts";
export type { KentekenVoertuigenBijzonderheden_ResponseData } from "./KentekenVoertuigenBijzonderheden.ts";
export { KentekenVoertuigenBrandstof } from "./KentekenVoertuigenBrandstof.ts";
export type { KentekenVoertuigenBrandstof_ResponseData } from "./KentekenVoertuigenBrandstof.ts";
export { KentekenVoertuigenCarrosserie } from "./KentekenVoertuigenCarrosserie.ts";
export type { KentekenVoertuigenCarrosserie_ResponseData } from "./KentekenVoertuigenCarrosserie.ts";
export { KentekenVoertuigenCarrosserieSpecificatie } from "./KentekenVoertuigenCarrosserieSpecificatie.ts";
export type { KentekenVoertuigenCarrosserieSpecificatie_ResponseData } from "./KentekenVoertuigenCarrosserieSpecificatie.ts";
export { KentekenVoertuigenRupsbanden } from "./KentekenVoertuigenRupsbanden.ts";
export type { KentekenVoertuigenRupsbanden_ResponseData } from "./KentekenVoertuigenRupsbanden.ts";
export { KentekenVoertuigenSubcategorieVoertuig } from "./KentekenVoertuigenSubcategorieVoertuig.ts";
export type { KentekenVoertuigenSubcategorieVoertuig_ResponseData } from "./KentekenVoertuigenSubcategorieVoertuig.ts";
export { KentekenVoertuigenVoertuigklasse } from "./KentekenVoertuigenVoertuigklasse.ts";
export type { KentekenVoertuigenVoertuigklasse_ResponseData } from "./KentekenVoertuigenVoertuigklasse.ts";
export { Keuringen } from "./Keuringen.ts";
export type { Keuringen_ResponseData } from "./Keuringen.ts";
export { Locaties } from "./Locaties.ts";
export type { Locaties_ResponseData } from "./Locaties.ts";
export { Locaties } from "./Locaties.ts";
export type { Locaties_ResponseData } from "./Locaties.ts";
export { MeldingenKeuringsinstantie } from "./MeldingenKeuringsinstantie.ts";
export type { MeldingenKeuringsinstantie_ResponseData } from "./MeldingenKeuringsinstantie.ts";
export { ParkerenBetaalmethodeGebied } from "./ParkerenBetaalmethodeGebied.ts";
export type { ParkerenBetaalmethodeGebied_ResponseData } from "./ParkerenBetaalmethodeGebied.ts";
export { ParkerenBetaalmethodeVerkooppunt } from "./ParkerenBetaalmethodeVerkooppunt.ts";
export type { ParkerenBetaalmethodeVerkooppunt_ResponseData } from "./ParkerenBetaalmethodeVerkooppunt.ts";
export { ParkerenContactpersoon } from "./ParkerenContactpersoon.ts";
export type { ParkerenContactpersoon_ResponseData } from "./ParkerenContactpersoon.ts";
export { ParkerenGebied } from "./ParkerenGebied.ts";
export type { ParkerenGebied_ResponseData } from "./ParkerenGebied.ts";
export { ParkerenGebiedRegeling } from "./ParkerenGebiedRegeling.ts";
export type { ParkerenGebiedRegeling_ResponseData } from "./ParkerenGebiedRegeling.ts";
export { ParkerenGebiedsbeheerder } from "./ParkerenGebiedsbeheerder.ts";
export type { ParkerenGebiedsbeheerder_ResponseData } from "./ParkerenGebiedsbeheerder.ts";
export { ParkerenGebruiksdoel } from "./ParkerenGebruiksdoel.ts";
export type { ParkerenGebruiksdoel_ResponseData } from "./ParkerenGebruiksdoel.ts";
export { ParkerenGeldigheidsinperking } from "./ParkerenGeldigheidsinperking.ts";
export type { ParkerenGeldigheidsinperking_ResponseData } from "./ParkerenGeldigheidsinperking.ts";
export { ParkerenGeldigheidsuitbreiding } from "./ParkerenGeldigheidsuitbreiding.ts";
export type { ParkerenGeldigheidsuitbreiding_ResponseData } from "./ParkerenGeldigheidsuitbreiding.ts";
export { ParkerenGeometrieGebied } from "./ParkerenGeometrieGebied.ts";
export type { ParkerenGeometrieGebied_ResponseData } from "./ParkerenGeometrieGebied.ts";
export { ParkerenGeoVerkooppunt } from "./ParkerenGeoVerkooppunt.ts";
export type { ParkerenGeoVerkooppunt_ResponseData } from "./ParkerenGeoVerkooppunt.ts";
export { ParkerenGpsCoordinatenParkeerlocatie } from "./ParkerenGpsCoordinatenParkeerlocatie.ts";
export type { ParkerenGpsCoordinatenParkeerlocatie_ResponseData } from "./ParkerenGpsCoordinatenParkeerlocatie.ts";
export { ParkerenIndexStatischEnDynamisch } from "./ParkerenIndexStatischEnDynamisch.ts";
export type { ParkerenIndexStatischEnDynamisch_ResponseData } from "./ParkerenIndexStatischEnDynamisch.ts";
export { ParkerenInUitgang } from "./ParkerenInUitgang.ts";
export type { ParkerenInUitgang_ResponseData } from "./ParkerenInUitgang.ts";
export { ParkerenParkeeradres } from "./ParkerenParkeeradres.ts";
export type { ParkerenParkeeradres_ResponseData } from "./ParkerenParkeeradres.ts";
export { ParkerenParkeergebied } from "./ParkerenParkeergebied.ts";
export type { ParkerenParkeergebied_ResponseData } from "./ParkerenParkeergebied.ts";
export { ParkerenParkeergebiedContactpersoon } from "./ParkerenParkeergebiedContactpersoon.ts";
export type { ParkerenParkeergebiedContactpersoon_ResponseData } from "./ParkerenParkeergebiedContactpersoon.ts";
export { ParkerenParkingOpen } from "./ParkerenParkingOpen.ts";
export type { ParkerenParkingOpen_ResponseData } from "./ParkerenParkingOpen.ts";
export { ParkerenParkingToegang } from "./ParkerenParkingToegang.ts";
export type { ParkerenParkingToegang_ResponseData } from "./ParkerenParkingToegang.ts";
export { ParkerenRegeling } from "./ParkerenRegeling.ts";
export type { ParkerenRegeling_ResponseData } from "./ParkerenRegeling.ts";
export { ParkerenSpecialeDag } from "./ParkerenSpecialeDag.ts";
export type { ParkerenSpecialeDag_ResponseData } from "./ParkerenSpecialeDag.ts";
export { ParkerenSpecificatiesParkeergebied } from "./ParkerenSpecificatiesParkeergebied.ts";
export type { ParkerenSpecificatiesParkeergebied_ResponseData } from "./ParkerenSpecificatiesParkeergebied.ts";
export { ParkerenTariefberekening } from "./ParkerenTariefberekening.ts";
export type { ParkerenTariefberekening_ResponseData } from "./ParkerenTariefberekening.ts";
export { ParkerenTariefdeel } from "./ParkerenTariefdeel.ts";
export type { ParkerenTariefdeel_ResponseData } from "./ParkerenTariefdeel.ts";
export { ParkerenTijdvak } from "./ParkerenTijdvak.ts";
export type { ParkerenTijdvak_ResponseData } from "./ParkerenTijdvak.ts";
export { ParkerenVerkooppunt } from "./ParkerenVerkooppunt.ts";
export type { ParkerenVerkooppunt_ResponseData } from "./ParkerenVerkooppunt.ts";
export { ProductenCatalogus } from "./ProductenCatalogus.ts";
export type { ProductenCatalogus_ResponseData } from "./ProductenCatalogus.ts";
export { TellerstandoordeelTrendToelichting } from "./TellerstandoordeelTrendToelichting.ts";
export type { TellerstandoordeelTrendToelichting_ResponseData } from "./TellerstandoordeelTrendToelichting.ts";
export { TerugroepActie } from "./TerugroepActie.ts";
export type { TerugroepActie_ResponseData } from "./TerugroepActie.ts";
export { TerugroepActieRisico } from "./TerugroepActieRisico.ts";
export type { TerugroepActieRisico_ResponseData } from "./TerugroepActieRisico.ts";
export { TerugroepActieStatus } from "./TerugroepActieStatus.ts";
export type { TerugroepActieStatus_ResponseData } from "./TerugroepActieStatus.ts";
export { TerugroepInformerenEigenaar } from "./TerugroepInformerenEigenaar.ts";
export type { TerugroepInformerenEigenaar_ResponseData } from "./TerugroepInformerenEigenaar.ts";
export { TerugroepVoertuigMerkType } from "./TerugroepVoertuigMerkType.ts";
export type { TerugroepVoertuigMerkType_ResponseData } from "./TerugroepVoertuigMerkType.ts";
export { TgkAandrijvingUitvoering } from "./TgkAandrijvingUitvoering.ts";
export type { TgkAandrijvingUitvoering_ResponseData } from "./TgkAandrijvingUitvoering.ts";
export { TgkAsUitvoering } from "./TgkAsUitvoering.ts";
export type { TgkAsUitvoering_ResponseData } from "./TgkAsUitvoering.ts";
export { TgkBasisUitvoering } from "./TgkBasisUitvoering.ts";
export type { TgkBasisUitvoering_ResponseData } from "./TgkBasisUitvoering.ts";
export { TgkCarrosserieUitvoering } from "./TgkCarrosserieUitvoering.ts";
export type { TgkCarrosserieUitvoering_ResponseData } from "./TgkCarrosserieUitvoering.ts";
export { TgkEnergiebronUitvoering } from "./TgkEnergiebronUitvoering.ts";
export type { TgkEnergiebronUitvoering_ResponseData } from "./TgkEnergiebronUitvoering.ts";
export { TgkHandelsbenamingFabrikant } from "./TgkHandelsbenamingFabrikant.ts";
export type { TgkHandelsbenamingFabrikant_ResponseData } from "./TgkHandelsbenamingFabrikant.ts";
export { TgkIntrekkingTypegoedkeuring } from "./TgkIntrekkingTypegoedkeuring.ts";
export type { TgkIntrekkingTypegoedkeuring_ResponseData } from "./TgkIntrekkingTypegoedkeuring.ts";
export { TgkKoppelingUitvoering } from "./TgkKoppelingUitvoering.ts";
export type { TgkKoppelingUitvoering_ResponseData } from "./TgkKoppelingUitvoering.ts";
export { TgkMerkUitvoering } from "./TgkMerkUitvoering.ts";
export type { TgkMerkUitvoering_ResponseData } from "./TgkMerkUitvoering.ts";
export { TgkRupsbandsetUitvoering } from "./TgkRupsbandsetUitvoering.ts";
export type { TgkRupsbandsetUitvoering_ResponseData } from "./TgkRupsbandsetUitvoering.ts";
export { TgkSpecialeDoeleinden } from "./TgkSpecialeDoeleinden.ts";
export type { TgkSpecialeDoeleinden_ResponseData } from "./TgkSpecialeDoeleinden.ts";
export { TgkVersnellingUitvoering } from "./TgkVersnellingUitvoering.ts";
export type { TgkVersnellingUitvoering_ResponseData } from "./TgkVersnellingUitvoering.ts";
export { ToegevoegdeObjecten } from "./ToegevoegdeObjecten.ts";
export type { ToegevoegdeObjecten_ResponseData } from "./ToegevoegdeObjecten.ts";
