name: Update Providers (on demand)
on:
  workflow_dispatch:

jobs:
  release:
    name: Update Providers (on demand)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Fetch & Update Providers
        run: deno task fetch-data

      - name: Get changed files
        id: changed-files
        run: |
          echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      - name: List changed files
        run: |
          for file in ${{ steps.changed-files.outputs.changed_files }}; do
            echo "$file was changed"
          done
